### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#577]
This seems like a regression (was working in v0.15.0)

**Comment by codebytere** [comment]
Pretty sure this is https://github.com/electron/electron/pull/27582 - that this is fixed when one disables `nodeIntegrationInWorker` and only shows up on macOS and Linux only seemingly confirms this

**Comment by erickzhao** [comment]
Unfortunately, it seems like upgrading to a version of Electron that contains that fix (I tried v12.0.0) doesn't fix the issue. Intellisense still fails to load, and disabling `nodeIntegrationInWorker` fixes the problem.

**Comment by codebytere** [comment]
@erickzhao i'll keep digging then - mind if i assign myself to this?

**Comment by erickzhao** [comment]
@codebytere go for it!

Alternatively, I'm thinking of reverting https://github.com/electron/fiddle/commit/5e3a58896ebc771db0c7edbc10fecfbf30a1e48a and going back to the drawing board.
